In [3]:
#  GROUPBY ON IPL DATASET

import numpy as np
import pandas as pd

In [4]:
delivery=pd.read_csv('deliveries.csv.zip')

In [5]:
delivery.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [6]:
runs=delivery.groupby('batsman')

In [7]:
runs.get_group('V Kohli')    # in this case the no. of rows shows the no. of balls played by virat kohli

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150410,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,5,V Kohli,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150414,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,3,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150415,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,4,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150416,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,5,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,0,0,0,V Kohli,bowled,NaN

In [8]:
runs['batsman_runs'].sum()   # this will group all the batsmans list and sum all their runs infront of their names

batsman
A Ashish Reddy     280
A Chandila           4
A Chopra            53
A Choudhary         25
A Flintoff          62
                  ...
YV Takawale        192
Yashpal Singh       47
Younis Khan          3
Yuvraj Singh      2591
Z Khan             117
Name: batsman_runs, Length: 461, dtype: int64

In [9]:
runs['batsman_runs'].sum().sort_values(ascending=False).head(5)   # in this way we can find out the top 5 run scorer of ipl

batsman
SK Raina     4548
V Kohli      4423
RG Sharma    4207
G Gambhir    4132
DA Warner    4014
Name: batsman_runs, dtype: int64

In [10]:
runs['legbye_runs'].sum().sort_values(ascending=False)[['V Kohli']]   # this indicates that when V Kohli is on strike 39 legbye runs are scored

batsman
V Kohli    39
Name: legbye_runs, dtype: int64

In [26]:
mask=delivery['batsman_runs']==6
new_delivery=delivery[mask]

In [27]:
new_delivery.shape[0]

6523

In [28]:
new_delivery.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(5)

# IN THIS WAY WE CAN FIND THE TOP 5 BATSMAN WHO SCORES MOST SIXES IN IPL HISTORY

batsman
CH Gayle     266
SK Raina     174
RG Sharma    173
V Kohli      160
DA Warner    160
Name: batsman_runs, dtype: int64

In [30]:
vk=delivery[delivery['batsman']=='V Kohli']

In [32]:
vk.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending=False).head(10)

bowling_team
Chennai Super Kings        706
Delhi Daredevils           661
Kings XI Punjab            483
Mumbai Indians             447
Sunrisers Hyderabad        439
Kolkata Knight Riders      391
Deccan Chargers            306
Gujarat Lions              283
Rajasthan Royals           258
Rising Pune Supergiants    188
Name: batsman_runs, dtype: int64

In [41]:
def run_scored(batsman_name):
    vk=delivery[delivery['batsman']==batsman_name]
    return vk.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending=False).index[0]

In [42]:
run_scored('V Kohli')

'Chennai Super Kings'

In [44]:
run_scored('MS Dhoni')

'Royal Challengers Bangalore'